def guess_game
  prng = Random.new
  num = prng.rand(10) + 1
  puts 'guess the random number generated by the computer that is between 1 and 100'
  guess = gets.chomp.to_i
  idx = 1

  until guess == num
    if guess > num 
      puts "The number is lower than #{guess}.Guess again"
      idx += 1
      guess = gets.chomp.to_i
    elsif guess < num
      puts "The number is higher than #{guess}.Guess again"
      idx += 1
      guess = gets.chomp.to_i
    end
  end

  puts "You got it in #{idx} tries"
end

guess_game